from typing import ContextManager, Optional
from .terminal import Terminal as _Terminal

class Terminal(_Terminal):
    def getch(self) -> str: ...
    def kbhit(self, timeout: Optional[float] = ...) -> bool: ...
    def cbreak(self) -> ContextManager[None]: ...
    def raw(self) -> ContextManager[None]: ...
